sudo: True
language: python
python: 3.6      # current default Python on Travis CI
os: linux
env: RUNTIME=3.6 ETS_TOOLKIT=qt4 VTK=7
dist: focal
services:
  - xvfb

install:
  - sudo apt-get install libboost-all-dev
  - pip3 install vtk==8.1.2
  - pip3 install pyqt5
  - pip3 install -r requirements.txt
  - python3 setup.py build_ext --inplace
  - pip3 install .
  - pip3 install codecov



env:
  - CODECOV_TOKEN='8b34d257-0baf-49de-8cd7-d53db530073f'

script:
  - coverage run -m unittest tests/Unittest.py


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
