language: python
python:
  - "3.6"      # current default Python on Travis CI


install:
  - sudo apt-get install libproj-dev proj-data proj-bin libgeos-dev
  - pip install -r requirements.txt


script:

  - coverage run -m unittest Test/Unittest.py
