
sudo: True
language: python
python: 3.8      # current default Python on Travis CI
os: linux
env: RUNTIME=3.6 ETS_TOOLKIT=qt4 VTK=7
arch: amd64
dist: focal

services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"

install:
  - sudo apt-get install cmake
  - export QT_DEBUG_PLUGINS=1
  - sudo -E apt-get install --yes --no-install-recommends qtbase5-dev qttools5-dev qt5-default qttools5-dev-tools qt5-qmake liblog4cpp5-dev libfftw3-dev libqt5sql5-sqlite xvfb python3 python3-pip python3-lxml python3-numpy python3-pandas gdb;

  - sudo apt-get install gfortran
  - sudo apt install libxcb-image0
  - sudo apt install libxcb-keysyms1
  - sudo apt install libxcb-render-util0
  - sudo apt install libxcb-xkb1
  - sudo apt install libxkbcommon-x11-0

  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libboost-dev

  - sudo apt-get install -qq libegl1-mesa
  - pip3 install -r requirements.txt
  - git clone https://github.com/joeydumont/complex_bessel.git
  - mkdir complex_bessel/build
  - sudo cmake -DBUILD_TESTING=OFF ./complex_bessel && sudo make install
  - ls ..
  - ls .
  - sudo rm -rf cmake_install.cmake CMakeCache.txt CMakeFiles
  - sudo cmake . && sudo make all
  - ls ..
  - ls .
  - python3 setup.py build_ext --inplace

  - pip3 install codecov



env:
  - CODECOV_TOKEN='8b34d257-0baf-49de-8cd7-d53db530073f'

script:
  - coverage run -m unittest tests/Unittest.py


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
