sudo: True
language: python
python: 3.6      # current default Python on Travis CI
os: linux
dist: focal

install:
  - sudo apt-get install libproj-dev proj-data proj-bin libgeos-dev libboost-all-dev libeigen3-dev
  - pip3 install -r requirements.txt
  - python3 setup.py build_ext --inplace
  - pip3 install .
  - pip3 install codecov

services:
- xvfb

env:
  - CODECOV_TOKEN='8b34d257-0baf-49de-8cd7-d53db530073f'

script:
  - coverage run -m unittest tests/Unittest.py


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
