sudo: True
language: python
python: 3.6      # current default Python on Travis CI



install:
  - sudo apt-get install libproj-dev proj-data proj-bin libgeos-dev vtk6 python-vtk libboost-all-dev
  - pip3 install -r requirements.txt
  - python3 setup.py build_ext --inplace
  - pip3 install .
  - pip3 install codecov

env:
  - CODECOV_TOKEN='8b34d257-0baf-49de-8cd7-d53db530073f'

script:
  - coverage run -m unittest Test/Unittest.py


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
