language: python
python:
  - "3.6"      # current default Python on Travis CI


install:
  - sudo apt-get install libproj-dev proj-data proj-bin libgeos-dev vtk6 python-vtk libboost-all-dev
  - pip3 install -r requirements.txt
  - python3 setup.py build_ext --inplace
  - pip3 install .


script:

  - coverage run -m unittest Test/Unittest.py
