package:
  name: "pymiesim"
  version: 0.1.18

source:
  git_rev: 0.1.18
  git_url: https://github.com/MartinPdeS/PyMieSim

requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - numpy
    - pybind11
    - cython
  run:
    - scipy
    - matplotlib
    - python
    - mayavi
    - pandas
    - pip
    - https://github.com/cbrunet/fibermodes.git


about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: 'A package for light scattering simulations.'
