{% set name = "PyMieSim" %}
{% set version = "0.1.19" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 64a06ed801e4b17c383a4285951d67d60bb826cd1ed62069a2153e3ce78ace26

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - pybind11
    - mayavi
    - pandas
    - pip
    - python
    - scipy
  run:
    - matplotlib
    - pybind11
    - mayavi
    - pandas
    - python
    - scipy

test:
  imports:
    - PyMieSim

about:
  home: "https://github.com/MartinPdeS/PyMieSim"
  license: MIT
  license_family: MIT
  license_file:
  summary: "A package for light scattering simulations."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - MartinPdeS
